# Generated by Django 4.2.6 on 2023-10-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls1', '0004_alter_osoba_plec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'verbose_name_plural': 'Osoby'},
        ),
    ]
