# Generated by Django 4.2.7 on 2023-11-11 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls1', '0005_alter_osoba_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Teams'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='month_added',
        ),
        migrations.AddField(
            model_name='person',
            name='datetime_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
