# Generated by Django 4.2.7 on 2023-11-17 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls1', '0007_alter_osoba_data_dodania'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls1.team'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
