# Generated by Django 4.2.7 on 2023-11-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls1', '0009_osoba_datetime_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='datetime_added',
        ),
    ]
