# Generated by Django 4.2.7 on 2023-11-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls1', '0010_remove_osoba_datetime_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='shirt_size',
            field=models.CharField(choices=[('K', 'Kobieta'), ('M', 'Mezczyzna')], default='K', max_length=1),
        ),
    ]
