# Generated by Django 4.2.7 on 2023-11-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls1', '0011_osoba_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osoba',
            name='shirt_size',
        ),
    ]
