# Generated by Django 4.2.7 on 2023-11-17 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls1', '0013_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='wlasciciel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osoby', to=settings.AUTH_USER_MODEL),
        ),
    ]
