# Generated by Django 4.2.7 on 2023-11-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls1', '0014_alter_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('can_view_other_osoba', 'Can view other persons'), ('osoba_view', 'Can view osoba')], 'verbose_name_plural': 'Osoby'},
        ),
    ]
