# Generated by Django 4.2.7 on 2023-11-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls1', '0015_alter_osoba_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('osoba_view', 'Can view osoba')], 'verbose_name_plural': 'Osoby'},
        ),
    ]
