# Generated by Django 4.2.7 on 2023-11-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls1', '0016_alter_osoba_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('view_other_osoba', 'Wyświetl  osoby, których się nie dodało')], 'verbose_name_plural': 'Osoby'},
        ),
    ]
